version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run memory monitor daemon
          command: while true; do ps -u circleci eo pid,%cpu,%mem,vsize,rss,uname,args --sort=-rss >> ./memory-usage.txt; echo "----------" >> ./memory-usage.txt; sleep 1; done
          background: true


      - run: ./gradlew --info test

      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports/tests
          destination: tests
      - store_artifacts:
          path: ./memory-usage.txt  #circleCI doesn't resolve env vars in yml commands
          destination: memory-usage.txt